-- BlogCabin 전체 ERD — PostgreSQL DDL
-- Crowfoot 문서 "Blogville 전체 ERD"(v5)에서 내보낸 DDL. 테이블·컬럼 설명(COMMENT)은 Crowfoot 문서와 README.md에 있다.
-- 원천: https://crowfoot.java21.net/workspaces/43/models/661

CREATE TABLE users (
    id VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    image TEXT,
    username VARCHAR(20),
    display_username VARCHAR(20),
    role VARCHAR(10) NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT users_role_check CHECK (role IN ('user', 'admin')),
    CONSTRAINT users_username_check CHECK (username IS NULL OR username ~ '^[a-z0-9_]{4,20}$')
);
CREATE TABLE accounts (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    provider_id VARCHAR(20) NOT NULL,
    account_id VARCHAR(255) NOT NULL,
    password TEXT,
    access_token TEXT,
    refresh_token TEXT,
    id_token TEXT,
    access_token_expires_at TIMESTAMPTZ,
    refresh_token_expires_at TIMESTAMPTZ,
    scope TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT accounts_pk PRIMARY KEY (id),
    CONSTRAINT uk_accounts_provider_id_account_id UNIQUE (provider_id, account_id),
    CONSTRAINT accounts_provider_check CHECK (provider_id IN ('credential', 'kakao', 'naver', 'google'))
);
CREATE TABLE sessions (
    id VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    token VARCHAR(255) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    ip_address VARCHAR(45),
    user_agent TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT sessions_pk PRIMARY KEY (id),
    CONSTRAINT uk_sessions_token UNIQUE (token)
);
CREATE TABLE verifications (
    id VARCHAR(64) NOT NULL,
    identifier VARCHAR(255) NOT NULL,
    value TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT verifications_pk PRIMARY KEY (id)
);
CREATE TABLE profiles (
    user_id VARCHAR(64) NOT NULL,
    character_item_id INTEGER NOT NULL,
    invited_by VARCHAR(64),
    nickname VARCHAR(12) NOT NULL,
    invite_code CHAR(6) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT profiles_pk PRIMARY KEY (user_id),
    CONSTRAINT uk_profiles_nickname UNIQUE (nickname),
    CONSTRAINT uk_profiles_invite_code UNIQUE (invite_code),
    CONSTRAINT profiles_nickname_check CHECK (char_length(nickname) BETWEEN 2 AND 12),
    CONSTRAINT profiles_invite_code_check CHECK (invite_code ~ '^[A-HJ-NP-Z2-9]{6}$'),
    CONSTRAINT profiles_invited_by_check CHECK (invited_by IS NULL OR invited_by <> user_id)
);
CREATE TABLE blogs (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    owner_id VARCHAR(64) NOT NULL,
    background_item_id INTEGER NOT NULL,
    slug VARCHAR(20) NOT NULL,
    title VARCHAR(40) NOT NULL,
    description VARCHAR(160) NOT NULL DEFAULT '',
    roof_color VARCHAR(20),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT blogs_pk PRIMARY KEY (id),
    CONSTRAINT uk_blogs_owner_id UNIQUE (owner_id),
    CONSTRAINT uk_blogs_slug UNIQUE (slug),
    CONSTRAINT blogs_slug_check CHECK (char_length(slug) BETWEEN 3 AND 20 AND slug = lower(slug)),
    CONSTRAINT blogs_title_check CHECK (char_length(title) BETWEEN 1 AND 40),
    CONSTRAINT blogs_description_check CHECK (char_length(description) <= 160)
);
CREATE TABLE categories (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    blog_id INTEGER NOT NULL,
    name VARCHAR(20) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT categories_pk PRIMARY KEY (id),
    CONSTRAINT categories_blog_name_uq UNIQUE (blog_id, name),
    CONSTRAINT categories_name_check CHECK (char_length(name) BETWEEN 1 AND 20)
);
CREATE TABLE blog_visits (
    blog_id INTEGER NOT NULL,
    visit_date DATE NOT NULL,
    visitor_key VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT blog_visits_pk PRIMARY KEY (blog_id, visit_date, visitor_key)
);
CREATE TABLE posts (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    category_id INTEGER,
    blog_id INTEGER NOT NULL,
    title VARCHAR(100) NOT NULL,
    content_html TEXT NOT NULL,
    content_text TEXT NOT NULL,
    visibility VARCHAR(10) NOT NULL DEFAULT 'public',
    view_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT posts_pk PRIMARY KEY (id),
    CONSTRAINT posts_title_check CHECK (char_length(title) BETWEEN 1 AND 100),
    CONSTRAINT posts_visibility_check CHECK (visibility IN ('public', 'private')),
    CONSTRAINT posts_view_count_check CHECK (view_count >= 0)
);
CREATE TABLE tags (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tags_pk PRIMARY KEY (id),
    CONSTRAINT uk_tags_name UNIQUE (name),
    CONSTRAINT tags_name_check CHECK (char_length(name) BETWEEN 1 AND 20 AND name = lower(name))
);
CREATE TABLE post_tags (
    post_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,
    CONSTRAINT post_tags_pk PRIMARY KEY (post_id, tag_id)
);
CREATE TABLE post_views (
    post_id INTEGER NOT NULL,
    view_date DATE NOT NULL,
    viewer_key VARCHAR(80) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_views_pk PRIMARY KEY (post_id, view_date, viewer_key)
);
CREATE TABLE attachments (
    key VARCHAR(64) NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    kind VARCHAR(10) NOT NULL,
    name VARCHAR(255) NOT NULL,
    mime VARCHAR(100) NOT NULL,
    size INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attachments_pk PRIMARY KEY (key),
    CONSTRAINT attachments_kind_check CHECK (kind IN ('image', 'file')),
    CONSTRAINT attachments_size_check CHECK (size > 0)
);
CREATE TABLE comments (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    parent_id INTEGER,
    author_id VARCHAR(64),
    post_id INTEGER NOT NULL,
    content VARCHAR(1000) NOT NULL,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT comments_pk PRIMARY KEY (id),
    CONSTRAINT comments_content_check CHECK (char_length(content) BETWEEN 1 AND 1000),
    CONSTRAINT comments_parent_check CHECK (parent_id IS NULL OR parent_id <> id)
);
CREATE TABLE post_likes (
    post_id INTEGER NOT NULL,
    user_id VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_likes_pk PRIMARY KEY (post_id, user_id)
);
CREATE TABLE follows (
    follower_id VARCHAR(64) NOT NULL,
    blog_id INTEGER NOT NULL,
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT follows_pk PRIMARY KEY (follower_id, blog_id)
);
CREATE TABLE items (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(40) NOT NULL,
    type VARCHAR(20) NOT NULL,
    slot VARCHAR(20),
    name VARCHAR(40) NOT NULL,
    description VARCHAR(200) NOT NULL DEFAULT '',
    asset_key VARCHAR(60) NOT NULL,
    price INTEGER NOT NULL DEFAULT 0,
    required_level INTEGER NOT NULL DEFAULT 1,
    is_starter BOOLEAN NOT NULL DEFAULT FALSE,
    is_on_sale BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT items_pk PRIMARY KEY (id),
    CONSTRAINT uk_items_code UNIQUE (code),
    CONSTRAINT items_type_check CHECK (type IN ('character', 'background', 'avatar', 'furniture')),
    CONSTRAINT items_slot_check CHECK ((type = 'avatar' AND slot IS NOT NULL AND slot IN ('hat', 'outfit', 'accessory')) OR (type <> 'avatar' AND slot IS NULL)),
    CONSTRAINT items_price_check CHECK (price >= 0),
    CONSTRAINT items_required_level_check CHECK (required_level >= 1)
);
CREATE TABLE user_items (
    user_id VARCHAR(64) NOT NULL,
    item_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_items_pk PRIMARY KEY (user_id, item_id)
);
CREATE TABLE avatar_wears (
    user_id VARCHAR(64) NOT NULL,
    slot VARCHAR(20) NOT NULL,
    item_id INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT avatar_wears_pk PRIMARY KEY (user_id, slot),
    CONSTRAINT uk_avatar_wears_user_id_item_id UNIQUE (user_id, item_id),
    CONSTRAINT avatar_wears_slot_check CHECK (slot IN ('hat', 'outfit', 'accessory'))
);
CREATE TABLE room_furniture (
    user_id VARCHAR(64) NOT NULL,
    item_id INTEGER NOT NULL,
    x_ratio DECIMAL(5,2) NOT NULL,
    y_ratio DECIMAL(5,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT room_furniture_pk PRIMARY KEY (user_id, item_id),
    CONSTRAINT room_furniture_x_check CHECK (x_ratio BETWEEN 0 AND 100),
    CONSTRAINT room_furniture_y_check CHECK (y_ratio BETWEEN 0 AND 100)
);
CREATE TABLE point_ledger (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id VARCHAR(64) NOT NULL,
    reason VARCHAR(30) NOT NULL,
    exp_delta INTEGER NOT NULL DEFAULT 0,
    coin_delta INTEGER NOT NULL DEFAULT 0,
    ref_id VARCHAR(80) NOT NULL,
    reward_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT point_ledger_pk PRIMARY KEY (id),
    CONSTRAINT point_ledger_once_uq UNIQUE (user_id, reason, ref_id),
    CONSTRAINT point_ledger_reason_check CHECK (reason IN ('signup', 'attendance', 'attendance_streak', 'post', 'comment', 'like_received', 'purchase', 'invite', 'invited', 'farm_care', 'farm_grown', 'egg_purchase')),
    CONSTRAINT point_ledger_exp_check CHECK (exp_delta >= 0)
);
CREATE TABLE attendances (
    user_id VARCHAR(64) NOT NULL,
    attend_date DATE NOT NULL,
    streak INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT attendances_pk PRIMARY KEY (user_id, attend_date),
    CONSTRAINT attendances_streak_check CHECK (streak >= 1)
);
CREATE TABLE notifications (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    post_id INTEGER,
    actor_id VARCHAR(64),
    user_id VARCHAR(64) NOT NULL,
    kind VARCHAR(20) NOT NULL,
    level INTEGER,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pk PRIMARY KEY (id),
    CONSTRAINT notifications_kind_check CHECK (kind IN ('level_up', 'like', 'comment', 'reply')),
    CONSTRAINT notifications_shape_check CHECK ((kind = 'level_up' AND level IS NOT NULL AND level BETWEEN 2 AND 99 AND actor_id IS NULL) OR (kind <> 'level_up' AND actor_id IS NOT NULL AND post_id IS NOT NULL))
);
CREATE TABLE animal_species (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(30) NOT NULL,
    name VARCHAR(20) NOT NULL,
    grow_target INTEGER NOT NULL,
    reward_exp INTEGER NOT NULL,
    reward_coin INTEGER NOT NULL,
    hatch_weight INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT animal_species_pk PRIMARY KEY (id),
    CONSTRAINT uk_animal_species_code UNIQUE (code),
    CONSTRAINT animal_species_values_check CHECK (grow_target > 0 AND reward_exp >= 0 AND reward_coin >= 0 AND hatch_weight > 0)
);
CREATE TABLE user_animals (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    species_id INTEGER,
    user_id VARCHAR(64) NOT NULL,
    source VARCHAR(10) NOT NULL,
    egg_key VARCHAR(20),
    growth INTEGER NOT NULL DEFAULT 0,
    hatched_at TIMESTAMPTZ,
    grown_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_animals_pk PRIMARY KEY (id),
    CONSTRAINT user_animals_free_egg_uq UNIQUE (user_id, egg_key),
    CONSTRAINT user_animals_source_check CHECK (source IN ('first', 'level', 'purchase')),
    CONSTRAINT user_animals_egg_key_check CHECK ((source = 'purchase' AND egg_key IS NULL) OR (source = 'first' AND egg_key IS NOT NULL AND egg_key = 'first') OR (source = 'level' AND egg_key IS NOT NULL AND egg_key LIKE 'level:%')),
    CONSTRAINT user_animals_hatch_check CHECK ((species_id IS NULL) = (hatched_at IS NULL)),
    CONSTRAINT user_animals_grown_check CHECK (grown_at IS NULL OR species_id IS NOT NULL),
    CONSTRAINT user_animals_growth_check CHECK (growth >= 0)
);
CREATE TABLE animal_cares (
    animal_id INTEGER NOT NULL,
    care_type VARCHAR(10) NOT NULL,
    care_date DATE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT animal_cares_pk PRIMARY KEY (animal_id, care_type, care_date),
    CONSTRAINT animal_cares_type_check CHECK (care_type IN ('feed', 'water', 'pet'))
);

ALTER TABLE accounts ADD CONSTRAINT fk_accounts_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE sessions ADD CONSTRAINT fk_sessions_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE profiles ADD CONSTRAINT fk_profiles_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE profiles ADD CONSTRAINT fk_profiles_profiles FOREIGN KEY (invited_by) REFERENCES profiles (user_id) ON DELETE SET NULL;
ALTER TABLE profiles ADD CONSTRAINT fk_profiles_user_items FOREIGN KEY (user_id, character_item_id) REFERENCES user_items (user_id, item_id);
ALTER TABLE blogs ADD CONSTRAINT fk_blogs_profiles FOREIGN KEY (owner_id) REFERENCES profiles (user_id) ON DELETE CASCADE;
ALTER TABLE blogs ADD CONSTRAINT fk_blogs_user_items FOREIGN KEY (owner_id, background_item_id) REFERENCES user_items (user_id, item_id);
ALTER TABLE categories ADD CONSTRAINT fk_categories_blogs FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE;
ALTER TABLE blog_visits ADD CONSTRAINT fk_blog_visits_blogs FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE;
ALTER TABLE posts ADD CONSTRAINT fk_posts_blogs FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE;
ALTER TABLE posts ADD CONSTRAINT fk_posts_categories FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE SET NULL;
ALTER TABLE post_tags ADD CONSTRAINT fk_post_tags_posts FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE post_tags ADD CONSTRAINT fk_post_tags_tags FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE;
ALTER TABLE post_views ADD CONSTRAINT fk_post_views_posts FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE attachments ADD CONSTRAINT fk_attachments_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT fk_comments_posts FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE comments ADD CONSTRAINT fk_comments_profiles FOREIGN KEY (author_id) REFERENCES profiles (user_id) ON DELETE SET NULL;
ALTER TABLE comments ADD CONSTRAINT fk_comments_comments FOREIGN KEY (parent_id) REFERENCES comments (id) ON DELETE CASCADE;
ALTER TABLE post_likes ADD CONSTRAINT fk_post_likes_posts FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE post_likes ADD CONSTRAINT fk_post_likes_profiles FOREIGN KEY (user_id) REFERENCES profiles (user_id) ON DELETE CASCADE;
ALTER TABLE follows ADD CONSTRAINT fk_follows_profiles FOREIGN KEY (follower_id) REFERENCES profiles (user_id) ON DELETE CASCADE;
ALTER TABLE follows ADD CONSTRAINT fk_follows_blogs FOREIGN KEY (blog_id) REFERENCES blogs (id) ON DELETE CASCADE;
ALTER TABLE user_items ADD CONSTRAINT fk_user_items_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_items ADD CONSTRAINT fk_user_items_items FOREIGN KEY (item_id) REFERENCES items (id) ON DELETE RESTRICT;
ALTER TABLE avatar_wears ADD CONSTRAINT fk_avatar_wears_user_items FOREIGN KEY (user_id, item_id) REFERENCES user_items (user_id, item_id) ON DELETE CASCADE;
ALTER TABLE room_furniture ADD CONSTRAINT fk_room_furniture_user_items FOREIGN KEY (user_id, item_id) REFERENCES user_items (user_id, item_id) ON DELETE CASCADE;
ALTER TABLE point_ledger ADD CONSTRAINT fk_point_ledger_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE attendances ADD CONSTRAINT fk_attendances_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_profiles FOREIGN KEY (actor_id) REFERENCES profiles (user_id) ON DELETE CASCADE;
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_posts FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE;
ALTER TABLE user_animals ADD CONSTRAINT fk_user_animals_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE user_animals ADD CONSTRAINT fk_user_animals_animal_species FOREIGN KEY (species_id) REFERENCES animal_species (id) ON DELETE RESTRICT;
ALTER TABLE animal_cares ADD CONSTRAINT fk_animal_cares_user_animals FOREIGN KEY (animal_id) REFERENCES user_animals (id) ON DELETE CASCADE;

CREATE INDEX idx_accounts_user_id ON accounts (user_id ASC);
CREATE INDEX idx_sessions_user_id ON sessions (user_id ASC);
CREATE INDEX idx_verifications_identifier ON verifications (identifier ASC);
CREATE INDEX idx_profiles_invited_by ON profiles (invited_by ASC);
CREATE INDEX idx_profiles_user_id_character_item_id ON profiles (user_id ASC, character_item_id ASC);
CREATE INDEX idx_blogs_owner_id_background_item_id ON blogs (owner_id ASC, background_item_id ASC);
CREATE INDEX idx_categories_blog_id ON categories (blog_id ASC);
CREATE INDEX idx_posts_blog_id_created_at ON posts (blog_id ASC, created_at DESC);
CREATE INDEX idx_posts_visibility_created_at ON posts (visibility ASC, created_at DESC);
CREATE INDEX idx_posts_blog_id ON posts (blog_id ASC);
CREATE INDEX idx_posts_category_id ON posts (category_id ASC);
CREATE INDEX idx_attachments_user_id_created_at ON attachments (user_id ASC, created_at ASC);
CREATE INDEX idx_attachments_user_id ON attachments (user_id ASC);
CREATE INDEX idx_comments_post_id_created_at ON comments (post_id ASC, created_at ASC);
CREATE INDEX idx_comments_post_id ON comments (post_id ASC);
CREATE INDEX idx_comments_author_id ON comments (author_id ASC);
CREATE INDEX idx_comments_parent_id ON comments (parent_id ASC);
CREATE INDEX idx_follows_follower_id_is_favorite ON follows (follower_id ASC, is_favorite ASC);
CREATE INDEX idx_items_type_required_level ON items (type ASC, required_level ASC);
CREATE INDEX idx_avatar_wears_user_id_item_id ON avatar_wears (user_id ASC, item_id ASC);
CREATE INDEX idx_point_ledger_user_id_reason_reward_date ON point_ledger (user_id ASC, reason ASC, reward_date ASC);
CREATE INDEX idx_point_ledger_user_id_created_at ON point_ledger (user_id ASC, created_at DESC);
CREATE INDEX idx_point_ledger_user_id ON point_ledger (user_id ASC);
CREATE INDEX idx_notifications_user_id_read_at_created_at ON notifications (user_id ASC, read_at ASC, created_at DESC);
CREATE INDEX idx_notifications_user_id ON notifications (user_id ASC);
CREATE INDEX idx_notifications_actor_id ON notifications (actor_id ASC);
CREATE INDEX idx_notifications_post_id ON notifications (post_id ASC);
CREATE INDEX idx_user_animals_user_id_grown_at ON user_animals (user_id ASC, grown_at ASC);
CREATE INDEX idx_user_animals_user_id ON user_animals (user_id ASC);
CREATE INDEX idx_user_animals_species_id ON user_animals (species_id ASC);
